language: php

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    # Minimum supported versions
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-lowest"

    - php: 7.3
      env: COVERAGE=true PHPUNIT_FLAGS="-v --coverage-text"

    # Symfony 4
    - php: 7.3
      env: SYMFONY_VERSION="^4"

      # Latest commit to master
    - php: 7.3
      env: STABILITY="dev"

  allow_failures:
    # Dev-master is allowed to fail.
    - env: STABILITY="dev"

branches:
  only:
    - master
    - travis
    # Build maintenance branches for older releases if needed. such branches should be named like "1.2"
    - '/^\d+\.\d+$/'

before_install:
  - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
  - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;

install:
  - composer update $COMPOSER_FLAGS --prefer-dist --no-interaction
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update dunglas/symfony-lock=$SYMFONY_VERSION; fi;

before_script:
  - mkdir -p build/logs
  - phpenv config-add .travis/php.ini
  - mysql -u root -e 'CREATE DATABASE encryptbundle;'
  - mysql -u root -e "CREATE USER 'encryptbundle'@'localhost' IDENTIFIED BY 'encryptbundle';"
  - mysql -u root -e "GRANT ALL ON encryptbundle.* TO 'encryptbundle'@'localhost';"

script:
  - composer validate --strict --no-check-lock
  - vendor/bin/phpunit $PHPUNIT_FLAGS

after_success:
  - travis_retry php vendor/bin/php-coveralls
  # or enable logging
  - travis_retry php vendor/bin/php-coveralls -v
